backend_repo      = "https://github.com/teresa2625/booking-system-backend.git"
backend_repo_name = "booking-system-backend"
aws_account_id    = "713292987965"
github_org        = "teresa2625"
db_username        = "myuser"
db_password        = "mypassword"
